# Generated by Django 2.1 on 2020-07-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passportno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phoneNumber',
        ),
    ]
