# Generated by Django 2.1 on 2020-07-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0002_auto_20200725_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='troll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yo', models.CharField(max_length=12)),
            ],
        ),
    ]
