# Generated by Django 2.1 on 2020-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0003_troll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='troll',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='passportno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
