# Generated by Django 2.1 on 2020-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0004_auto_20200725_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
