# Generated by Django 2.1 on 2020-07-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0006_auto_20200725_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='box.jpg', upload_to=''),
        ),
    ]
